import type { Metadata } from 'next';
import '@styles/global.scss';
import styles from './layout.module.scss';

export const metadata: Metadata = {
	title: 'Nicklas Lydersen',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={styles.main}>{children}</body>
		</html>
	);
}
